chore: updates

diff --git a/tekton/base/ansible-task.yaml b/tekton/base/ansible-task.yaml
--- a/tekton/base/ansible-task.yaml
+++ b/tekton/base/ansible-task.yaml
@@ -80,7 +80,7 @@ spec:
         CI_JOB_JWT="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"
         export CI_JOB_JWT
         export VAULT_ADDR=https://vault.${URL}
-        VAULT_TOKEN="$(vault write -field=token auth/homelab/login role=homelab jwt=${CI_JOB_JWT})"
+        VAULT_TOKEN="$(vault write -field=token auth/homelab/login role=homelab jwt="${CI_JOB_JWT}")"
         export VAULT_TOKEN
         SSH_KNOWN_HOSTS="$(vault kv get -field=known_hosts secret/gitlab/ssh)"
         export SSH_KNOWN_HOSTS
@@ -93,21 +93,22 @@ spec:
 
         DISCORD="$(vault kv get -field=webhook secret/gitlab/discord)"
         export DISCORD
-        sed -i "s,REPLACE_ME,${DISCORD},g" ${WORKSPACE_DATA_PATH}/machineConfigs/servers/server/home/arthur/discord/discord_bot.sh
-        sed -i "s,REPLACE_ME,${URL},g" ${WORKSPACE_DATA_PATH}/machineConfigs/servers/kvm-1/etc/promtail/config.yml
-        sed -i "s,REPLACE_ME,${URL},g" ${WORKSPACE_DATA_PATH}/machineConfigs/servers/kvm-2/etc/promtail/config.yml
-        sed -i "s,REPLACE_ME,${URL},g" ${WORKSPACE_DATA_PATH}/machineConfigs/servers/k3s-server/etc/promtail/config.yml
+        sed -i "s,REPLACE_ME,${DISCORD},g" "${WORKSPACE_DATA_PATH}"/machineConfigs/servers/server/home/arthur/discord/discord_bot.sh
+        sed -i "s,REPLACE_ME,${URL},g" "${WORKSPACE_DATA_PATH}"/machineConfigs/servers/kvm-1/etc/promtail/config.yml
+        sed -i "s,REPLACE_ME,${URL},g" "${WORKSPACE_DATA_PATH}"/machineConfigs/servers/kvm-2/etc/promtail/config.yml
+        sed -i "s,REPLACE_ME,${URL},g" "${WORKSPACE_DATA_PATH}"/machineConfigs/servers/k3s-server/etc/promtail/config.yml
 
         mkdir -p ~/.ssh
         chmod 700 ~/.ssh
-        echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
+        echo "${SSH_KNOWN_HOSTS}" >> ~/.ssh/known_hosts
         chmod 644 ~/.ssh/known_hosts
-        echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_ed25519
+        echo "${SSH_PRIVATE_KEY}" >> ~/.ssh/id_ed25519
         chmod 600 ~/.ssh/id_ed25519
-        eval "$(ssh-agent)" > /dev/null
+        SSH_AGENT_ENV=$(ssh-agent) || { echo "Failed to start ssh-agent"; exit 1; }
+        eval "$SSH_AGENT_ENV"
         ssh-add ~/.ssh/id_ed25519
 
-        echo "$PULL_SECRET" > /tmp/pull_secret.json
+        echo "${PULL_SECRET}" > /tmp/pull_secret.json
 
         export CHECK=""
         if [[ "${DRY_RUN}" = "true" ]]; then
@@ -116,10 +117,9 @@ spec:
 
         for PLAYBOOK in ${PLAYBOOKS//,/ }
         do
-        sed -i "s,##,,g"  ${WORKSPACE_DATA_PATH}/ansible/${PLAYBOOK}.yaml
-        ansible-playbook -e "ansible_ssh_timeout=1" -i ${WORKSPACE_DATA_PATH}/ansible/inventory ${WORKSPACE_DATA_PATH}/ansible/${PLAYBOOK}.yaml \
-          --extra-vars "ansible_become_pass=${SUDO} ansible_ssh_pass=${SUDO} \
-          ansible_python_interpreter=/usr/bin/python3" -e 'ansible_python_interpreter=/usr/bin/python3' ${CHECK}
+        sed -i "s,##,,g"  "${WORKSPACE_DATA_PATH}"/ansible/"${PLAYBOOK}".yaml
+        ansible-playbook -e "ansible_ssh_timeout=1" -i "${WORKSPACE_DATA_PATH}"/ansible/inventory "${WORKSPACE_DATA_PATH}"/ansible/"${PLAYBOOK}".yaml \
+          --extra-vars "ansible_become_pass=\"${SUDO}\" ansible_ssh_pass=\"${SUDO}\" ansible_python_interpreter=/usr/bin/python3" -e 'ansible_python_interpreter=/usr/bin/python3' "${CHECK}"
         done
   volumes:
     - name: ssh
